name: Debian Package Build

on:
  release:
    types:
      - published

env:
  DEBIAN_FRONTEND: noninteractive
  DEBEMAIL: packaging@wand.net.nz
  DEBFULLNAME: WAND Packaging

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Build matrix
        id: set-matrix
        run: |
          git_tmp_dir=$(mktemp -d /tmp/distro-info-data-XXXXX)
          git clone --depth 1 https://salsa.debian.org/debian/distro-info-data "${git_tmp_dir}"
          releases=()
          for release in $(awk -F ',' -v today="$(date --utc "+%F")" \
              'BEGIN {OFS=","} NR>1 { if (($6 == "" || $6 >= today) && ($5 != "" && $5 <= today)) print $3 }' \
              "${git_tmp_dir}/ubuntu.csv"); do
              releases+=("ubuntu:${release}")
          done
          for release in $(awk -F ',' -v today="$(date --utc "+%F")" \
              'BEGIN {OFS=","} NR>1 { if (($6 == "" || $6 >= today) && ($4 != "" && $4 <= today)) print $3 }' \
              "${git_tmp_dir}/debian.csv" | grep -v -E "(sid|experimental)"); do
              releases+=("debian:${release}")
          done
          releases+=("debian:stretch")
          matrix=$(printf "%s\n" "${releases[@]}" | jq -nRc '[inputs]')
          echo "::set-output name=matrix::${matrix}"

  build:
    runs-on: ubuntu-latest
    needs: build-matrix
    container:
      image: ${{ matrix.target }}
    strategy:
      matrix:
        arch:
          - amd64
        target: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs
      - name: Remove dh-systemd from build dependencies
        run: |
          if dpkg --compare-versions "$(dpkg-query --showformat='${Version}' --show debhelper)" ge 13.3; then
            sed -i 's/Build-Depends: debhelper (>= 9), dh-systemd/Build-Depends: debhelper (>= 9)/' debian/control
          fi
      - name: Build package
        run: |
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot
          dirname=$(echo ${{ matrix.target }} | tr ':' '_')
          package_path="${GITHUB_WORKSPACE}/packages/${dirname}"
          mkdir -p "${package_path}"
          mv ../*.deb "${package_path}"
