name: Debian Package Build

on:
  release:
    types:
      - published

env:
  DEBIAN_FRONTEND: noninteractive
  DEBEMAIL: packaging@wand.net.nz
  DEBFULLNAME: WAND Packaging

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.target }}
    strategy:
      matrix:
        arch:
          - amd64
        target:
            - "ubuntu:focal"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
      - name: Build package
        run: |
          dpkg-buildpackage -b -us -uc -rfakeroot
      - name: Store package
        run: |
          mkdir -p packages/all
          cp ../*.deb packages/all
      - name: Publish packages to cloudsmith
        uses: wanduow/action-cloudsmith-upload-packages@v1
        with:
          path: packages/
          repo: wand/systemd-named-netns
          username: brad-cowie
          api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
